### ISSUE TITLE
Sound cut-off when play wav in front-end

### ISSUE THREAD

**Issue by Developer-jin** [xen-troops/snd_be#34]
I run this backend in linux domain and use android domain as frontend, kernel version is 4.19,
and I use [tinyplay 1.wav] to play sound in android console, the sound is cutting-off with long  clips.
Are there any advice about this issue? Thank you very much!

**Comment by andr2000** [comment]
1. How is your Linux configured, e.g. ALSA, pulse?
2. If plain ALSA is used then it is possible that buffer size configured for Android needs to be the same as when you play in Linux

**Comment by Developer-jin** [comment]
I use ALSA in linux, and now I see this log occur in linux:
`ALSA` lib ../../../alsa-lib-1.1.5/src/pcm/pcm.c:8349:(snd_pcm_recover) underrun occurred

**Comment by rshym** [comment]
Developer-jin,
Could you please specify following info, so we will be able to reproduce reported issue:
- sample rate
- bits per sample
- number of channels
- total duration of audio
- 'cut-off' duration

I just played wav sample with format: 48000, 16 bits, 2 channels and duration 3m 40s. No cut-off were observed.

**Comment by Developer-jin** [comment]
Hi rshym,
I use `tinyplay 10KHZ.wav -p 1920 -n 3 ` to play wav in Android domain,
The sample rate is 48KHz, 16bits, 2 channel, the duration is 00:01:00.06 = 2882665 samples(see in sox command), the cut-off duration doesn't specified, but it is obvious.
And every time when sound cut-off occurred, print the log above.
I'm checking the buffer size in both side. Do you know where to set the buffer size?
Thank you!

**Comment by rshym** [comment]
Buffer size is specified in dom0 in file /xt/dom.cfg/doma.cfg section vsnd.
For example:
`vsnd = [[ 'card, backend=DomD, buffer-size=65536, ...`
Pay attention, that this file is not stored across reboot of board.

**Comment by Developer-jin** [comment]
I set this size 1048576, as sndif.h said the maximum size per stream ,
and are there any runtime buffer size to set?

**Comment by andr2000** [comment]
Could you please:
1. Play a file in Linux with the same exact format as you want Android to be configured,
e.g. number of channels, format etc.
2. Calculate the buffer size: e.g. num_channels*sample_size*... so you have this number in bytes
3. Configure Android (cfg file) to use buffer size form 2)

**Comment by Developer-jin** [comment]
Hi andr2000,
I use aplay play the same wav in linux， and it print：
`(XEN) [  759.962222] Playing WAVE '10KHZ.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
(XEN) [  759.972542] Plug PCM: Rate conversion PCM (44100, sformat=S16_LE)
(XEN) [  759.979847] Converter: linear-interpolation
(XEN) [  759.985065] Protocol version: 10002
(XEN) [  759.989524] Its setup is:
(XEN) [  759.993034]   stream       : PLAYBACK
(XEN) [  759.997683]   access       : RW_INTERLEAVED
(XEN) [  760.002901]   format       : S16_LE
(XEN) [  760.007360]   subformat    : STD
(XEN) [  760.011535]   channels     : 2
(XEN) [  760.015520]   rate         : 48000
(XEN) [  760.019884]   exact rate   : 48000 (48000/1)
(XEN) [  760.025197]   msbits       : 16
(XEN) [  760.029276]   buffer_size  : 5760
(XEN) [  760.033546]   period_size  : 1920
(XEN) [  760.037815]   period_time  : 40000
(XEN) [  760.042180]   tstamp_mode  : NONE
(XEN) [  760.046449]   tstamp_type  : MONOTONIC
(XEN) [  760.051193]   period_step  : 1
(XEN) [  760.055177]   avail_min    : 1920
(XEN) [  760.059447]   period_event : 0
(XEN) [  760.063432]   start_threshold  : 5760
(XEN) [  760.068080]   stop_threshold   : 5760
(XEN) [  760.072729]   silence_threshold: 0
(XEN) [  760.077094]   silence_size : 0
(XEN) [  760.081078]   boundary     : 6485183463413514240
(XEN) [  760.086771] Slave: Direct Stream Mixing PCM
(XEN) [  760.091989] Its setup is:
(XEN) [  760.095499]   stream       : PLAYBACK
(XEN) [  760.100148]   access       : MMAP_INTERLEAVED
(XEN) [  760.105556]   format       : S16_LE
(XEN) [  760.110015]   subformat    : STD
(XEN) [  760.114190]   channels     : 2
(XEN) [  760.118174]   rate         : 44100
(XEN) [  760.122539]   exact rate   : 44100 (44100/1)
(XEN) [  760.127852]   msbits       : 16
(XEN) [  760.131931]   buffer_size  : 5292
(XEN) [  760.136201]   period_size  : 1764
(XEN) [  760.140470]   period_time  : 40000
(XEN) [  760.144834]   tstamp_mode  : NONE
(XEN) [  760.149104]   tstamp_type  : MONOTONIC
(XEN) [  760.153847]   period_step  : 1
(XEN) [  760.157832]   avail_min    : 1764
(XEN) [  760.162101]   period_event : 0
(XEN) [  760.166086]   start_threshold  : 5292
(XEN) [  760.170737]   stop_threshold   : 5292
(XEN) [  760.175384]   silence_threshold: 0
(XEN) [  760.179748]   silence_size : 0
(XEN) [  760.183733]   boundary     : 5958262307011166208
(XEN) [  760.189426] Hardware PCM card 0 'wm8960-audio' device 0 subdevice 0
(XEN) [  760.196921] Its setup is:
(XEN) [  760.200431]   stream       : PLAYBACK
(XEN) [  760.205080]   access       : MMAP_INTERLEAVED
(XEN) [  760.210488]   format       : S16_LE
(XEN) [  760.214947]   subformat    : STD
(XEN) [  760.219121]   channels     : 2
(XEN) [  760.223106]   rate         : 44100
(XEN) [  760.227470]   exact rate   : 44100 (44100/1)
(XEN) [  760.232783]   msbits       : 16
(XEN) [  760.236863]   buffer_size  : 5292
(XEN) [  760.241133]   period_size  : 1764
(XEN) [  760.245402]   period_time  : 40000
(XEN) [  760.249766]   tstamp_mode  : ENABLE
(XEN) [  760.254225]   tstamp_type  : MONOTONIC
(XEN) [  760.258969]   period_step  : 1
(XEN) [  760.262954]   avail_min    : 1764
(XEN) [  760.267223]   period_event : 0
(XEN) [  760.271208]   start_threshold  : 1
(XEN) [  760.275572]   stop_threshold   : 5958262307011166208
(XEN) [  760.281644]   silence_threshold: 0
(XEN) [  760.286008]   silence_size : 5958262307011166208
(XEN) [  760.291701]   boundary     : 5958262307011166208
(XEN) [  760.297393]   appl_ptr     : 0
(XEN) [  760.301378]   hw_ptr       : 0
(XEN) [  761.616676] ^C(XEN) [  761.618856] Aborted by signal Interrupt...
(XEN) [  761.623979] aplay: pcm_write:2051: write error: Interrupted system call
root@imx8qmmek:~/wav# (XEN) [  788.480338] aplay -v 10KHZ.wav 
(XEN) [  789.296554] Playing WAVE '10KHZ.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
(XEN) [  789.306857] Plug PCM: Rate conversion PCM (44100, sformat=S16_LE)
(XEN) [  789.314164] Converter: linear-interpolation
(XEN) [  789.319380] Protocol version: 10002
(XEN) [  789.323839] Its setup is:
(XEN) [  789.327349]   stream       : PLAYBACK
(XEN) [  789.331998]   access       : RW_INTERLEAVED
(XEN) [  789.337216]   format       : S16_LE
(XEN) [  789.341675]   subformat    : STD
(XEN) [  789.345850]   channels     : 2
(XEN) [  789.349835]   rate         : 48000
(XEN) [  789.354199]   exact rate   : 48000 (48000/1)
(XEN) [  789.359512]   msbits       : 16
(XEN) [  789.363592]   buffer_size  : 5760
(XEN) [  789.367861]   period_size  : 1920
(XEN) [  789.372130]   period_time  : 40000
(XEN) [  789.376495]   tstamp_mode  : NONE
(XEN) [  789.380764]   tstamp_type  : MONOTONIC
(XEN) [  789.385508]   period_step  : 1
(XEN) [  789.389492]   avail_min    : 1920
(XEN) [  789.393762]   period_event : 0
(XEN) [  789.397747]   start_threshold  : 5760
(XEN) [  789.402396]   stop_threshold   : 5760
(XEN) [  789.407044]   silence_threshold: 0
(XEN) [  789.411408]   silence_size : 0
(XEN) [  789.415393]   boundary     : 6485183463413514240
(XEN) [  789.421086] Slave: Direct Stream Mixing PCM
(XEN) [  789.426306] Its setup is:
(XEN) [  789.429814]   stream       : PLAYBACK
(XEN) [  789.434463]   access       : MMAP_INTERLEAVED
(XEN) [  789.439871]   format       : S16_LE
(XEN) [  789.444330]   subformat    : STD
(XEN) [  789.448505]   channels     : 2
(XEN) [  789.452490]   rate         : 44100
(XEN) [  789.456856]   exact rate   : 44100 (44100/1)
(XEN) [  789.462167]   msbits       : 16
(XEN) [  789.466246]   buffer_size  : 5292
(XEN) [  789.470516]   period_size  : 1764
(XEN) [  789.474785]   period_time  : 40000
(XEN) [  789.479149]   tstamp_mode  : NONE
(XEN) [  789.483419]   tstamp_type  : MONOTONIC
(XEN) [  789.488164]   period_step  : 1
(XEN) [  789.492147]   avail_min    : 1764
(XEN) [  789.496417]   period_event : 0
(XEN) [  789.500403]   start_threshold  : 5292
(XEN) [  789.505050]   stop_threshold   : 5292
(XEN) [  789.509699]   silence_threshold: 0
(XEN) [  789.514063]   silence_size : 0
(XEN) [  789.518048]   boundary     : 5958262307011166208
(XEN) [  789.523741] Hardware PCM card 0 'wm8960-audio' device 0 subdevice 0
(XEN) [  789.531238] Its setup is:
(XEN) [  789.534746]   stream       : PLAYBACK
(XEN) [  789.539395]   access       : MMAP_INTERLEAVED
(XEN) [  789.544803]   format       : S16_LE
(XEN) [  789.549262]   subformat    : STD
(XEN) [  789.553437]   channels     : 2
(XEN) [  789.557421]   rate         : 44100
(XEN) [  789.561786]   exact rate   : 44100 (44100/1)
(XEN) [  789.567098]   msbits       : 16
(XEN) [  789.571178]   buffer_size  : 5292
(XEN) [  789.575448]   period_size  : 1764
(XEN) [  789.579717]   period_time  : 40000
(XEN) [  789.584081]   tstamp_mode  : ENABLE
(XEN) [  789.588540]   tstamp_type  : MONOTONIC
(XEN) [  789.593285]   period_step  : 1
(XEN) [  789.597269]   avail_min    : 1764
(XEN) [  789.601538]   period_event : 0
(XEN) [  789.605523]   start_threshold  : 1
(XEN) [  789.609887]   stop_threshold   : 5958262307011166208
(XEN) [  789.615959]   silence_threshold: 0
(XEN) [  789.620323]   silence_size : 5958262307011166208
(XEN) [  789.626016]   boundary     : 5958262307011166208
(XEN) [  789.631708]   appl_ptr     : 0
(XEN) [  789.635693]   hw_ptr       : 0
`

But I don't know how to calculate the buffersize from these data.

**Comment by andr2000** [comment]
(XEN) [  760.002901]   format       : S16_LE (2 bytes)
(XEN) [  760.011535]   channels     : 2 (multiply by 2)
(XEN) [  760.029276]   buffer_size  : 5760 (number of samples)

buffer_sz = 2 * 2 * 5760 = 23040

**Comment by Developer-jin** [comment]
Hi andr2000,
I use buffer-size=23040, the sound-cut still exists.
And the error log print about every 100ms:
`(XEN) [ 2074.209309] 04.01.19 02:47:59.732 | AlsaPcm        | WRN - Device: default, message: Broken pipe`
`(XEN) [ 2074.219553] ALSA lib ../../../alsa-lib-1.1.5/src/pcm/pcm.c:8349:(snd_pcm_recover) underrun occurred`
`(XEN) [ 2074.329671] 04.01.19 02:47:59.852 | AlsaPcm        | WRN - Device: default, message: Broken pipe`
`(XEN) [ 2074.339915] ALSA lib ../../../alsa-lib-1.1.5/src/pcm/pcm.c:8349:(snd_pcm_recover) underrun occurred`

**Comment by andr2000** [comment]
All these are because buffer size used by real HW and frontend driver do not match, e.g. the buffer selected by HW for the stream given is not equal to how front driver is configured. Fixing this should help.
You can also run pulse instead of ALSA in driver domain or have pulse ALSA plugin.

**Comment by Developer-jin** [comment]
Hi andr2000,
Snd_be only set buffer size by cfg? Are there any other place to set this param?

**Comment by andr2000** [comment]
1. buffer size in the domain configuration only
2. if it plays with pulse then it is definitely a buffer size problem, e.g. what you have in the domain config doesn't match what hardware uses
3. left channel - not sure this is relevant to the backend/frontend

**Comment by andr2000** [comment]
@Developer-jin any update?

**Comment by Developer-jin** [comment]
Hi andr2000,
I use snd_be with libpulse solve this problem, there is no sound cut-off.
And modify /etc/pulse/default.pa:
`load-module module-alsa-sink device=hw:0,0` could enable stereo.
Thank you very much!

**Comment by andr2000** [comment]
seems to be resolved

**Comment by jsharma80** [comment]
hi @andr2000 ,

I am trying to enable sound using ubuntu as "dom 0" as well as "dom U" (HVM) under xen. I am new to xen. Can you please guide me how do I go about this?
