### ISSUE TITLE
Selecting sound card with Pulse Audio back end

### ISSUE THREAD

**Issue by jsharma80** [xen-troops/snd_be#42]
Hello,

I have got audio working from HVM guest with Pulse Audio as back end. Following is my vsnd config:

vsnd = [[ 'card, backend=Domain-0, buffer-size=65536, short-name=VCard, long-name=Virtual sound card, sample-rates=44100, sample-formats=s16_le', 'pcm, name=dev1', 'stream, unique-id=pulse, type=P' ]]

Currently audio is playing through default sound card. However, I want to play it through another sound card present in Dom 0. How can I select the other sound card (say hw:2,0)?

I tried setting following parameter, but it did not work: unique-id=pulse<<hw:2;0>>

**Comment by al1img** [comment]
The format <hw:0;1> is relevant for alsa only. In case of pulse audio is used as backend, sink, or source (depending on stream type) name may be specified as _device_ parameter. You can use `pactl list` command to retrieve names of configured sinks and sources.

**Comment by jsharma80** [comment]
Thanks for the quick revert. Basically my requirement is to connect to different I2S controller for different Dom U. These I2S controllers are registered as ALSA sound cards. Is it possible to choose a specific ALSA sound card with Pulse Audio back end? I am trying this approach as ALSA back end is not working for me.

**Comment by al1img** [comment]
Yes, it is possible. If pulseaudio backend is configured properly, you should see all your alsa sound cards and their sinks in the output of `pactl list` command. Then just add sink name as _device_ parameter to stream id: `unique-id=pulse<sink_name>`.

Another approach is to use alsa backend and write directly to the device. According to your log from issue #40:

> card 1: Generic_1 [HD-Audio Generic], device 0: ALC898 Analog [ALC898 Analog]
> Subdevices: 1/1
> Subdevice #0: subdevice #0

If you would like the stream to be output to the above device, use `unique-id=alsa<hw:1;0>` (e.g. card 1, subdevice #0). 

Have you tried alsa backend with the certain device like `hw:1;0` instead of default one?

**Comment by jsharma80** [comment]
hi, 

>> Have you tried alsa backend with the certain device like hw:1;0 instead of default one?

Yes. I tried it using following vsnd config: unique-id=alsa<hw:1;0>

However, in this case I get following error and back end gets stuck. Any idea what could be going wrong?

14.09.22 18:53:21.001 | CommandHandler  | DBG - Handle command [QUERY_HW_PARAM]
14.09.22 18:53:21.001 | AlsaPcm         | DBG - Opening pcm device for queries: hw:1,0
14.09.22 18:53:21.001 | AlsaPcm         | DBG - Close pcm device: hw:1,0
**14.09.22 18:53:21.001 | CommandHandler  | ERR - Can't open audio device hw:1,0 (Device or resource busy)**
14.09.22 18:53:21.001 | CommandHandler  | DBG - Return status: [-16]
14.09.22 18:53:21.001 | XenEvtchn       | DBG - Notify event channel, port: 138
14.09.22 18:53:21.002 | XenEvtchn       | DBG - Event received, port: 138
14.09.22 18:53:21.002 | StreamRing      | DBG - Request received, id: alsa<hw:1;0>, cmd:1
14.09.22 18:53:21.002 | CommandHandler  | DBG - Handle command [CLOSE]

**Comment by al1img** [comment]
It could mean the device is allocated by some other process. Alsa devices are exclusive and can't be opened by multiple processes. I guess it is pulse plugin uses alsa devices.

Did you manage to get sink names by `pactl list` command?

I suggest either using pulse backend with the appropriate sink name or removing pulseaudio alsa plugin from alsa and playing by hw device directly.

**Comment by jsharma80** [comment]
>> Did you manage to get sink names by pactl list command?

Yes. Please see the log at the end of this post. It is listing my card under sink and I tried playing using pulse back end with this device: unique-id=pulse<alsa_output.platform-acp3x_w5102_mach.0.stereo-fallback>
However, I encountered following error in snd_be:

14.09.22 20:16:20.404 | CommandHandler  | ERR - Can't wait stream ready (No such entity)
14.09.22 20:16:20.404 | CommandHandler  | DBG - Return status: [-5]

>> I suggest either using pulse backend with the appropriate sink name or removing pulseaudio alsa plugin from alsa and playing by hw device directly.

Ok, my preference is ALSA as I am not much familiar with PA. I was trying PA as ALSA is not working as expected. Please refer to issue #40 on my latest status on ALSA back end and help me tune the buffer-size parameter.

Also, by "removing pulseaudio alsa plugin from alsa", did you mean removing Pulse Audio from snd_be and to try with ALSA back end only?

pactl_list log:

Sink #1
	State: RUNNING
	Name: alsa_output.platform-acp3x_w5102_mach.0.stereo-fallback
	Description: Built-in Audio Stereo
	Driver: module-alsa-card.c
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Owner Module: 25
	Mute: no
	Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
	        balance 0.00
	Base Volume: 65536 / 100% / 0.00 dB
	Monitor Source: alsa_output.platform-acp3x_w5102_mach.0.stereo-fallback.monitor
	Latency: 99892 usec, configured 99954 usec
	Flags: HARDWARE DECIBEL_VOLUME LATENCY 
	Properties:
		alsa.resolution_bits = "16"
		device.api = "alsa"
		device.class = "sound"
		alsa.class = "generic"
		alsa.subclass = "generic-mix"
		alsa.name = ""
		alsa.id = "Playback dummy_w5102.0-0"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		alsa.device = "0"
		alsa.card = "2"
		alsa.card_name = "acp3x"
		alsa.long_card_name = "AMD-Majolica_RN-1"
		alsa.driver_name = "snd_soc_acp3x_mach"
		device.bus_path = "platform-acp3x_w5102_mach.0"
		sysfs.path = "/devices/platform/acp3x_w5102_mach.0/sound/card2"
		device.form_factor = "internal"
		device.string = "hw:2"
		device.buffering.buffer_size = "17632"
		device.buffering.fragment_size = "4408"
		device.access_mode = "mmap"
		device.profile.name = "stereo-fallback"
		device.profile.description = "Stereo"
		device.description = "Built-in Audio Stereo"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card"
	Ports:
		analog-output: Analog Output (type: Analog, priority: 9900, availability unknown)
	Active Port: analog-output
	Formats:
		pcm

**Comment by al1img** [comment]
First of all, I wonder why the sink state is `running` in your case. It should be `idle`. It could be that some other process, or application uses this sink. Not sure if it is the root cause of the issue.

> Also, by "removing pulseaudio alsa plugin from alsa", did you mean removing Pulse Audio from snd_be and to try with ALSA back end only?

By removing pulsaudio alsa plugin I mean removing it from alsa configuration. As I can see, in your current configuration pulseaudio plugin is used as the default alsa device:
> ```sh
> amd@amd-HVM-domU:~$ aplay -L
> null
> Discard all samples (playback) or generate zero samples (capture)
> default
> Playback/recording through the PulseAudio sound server
> ```

Please see alsa documentation on how to configure alsa plugins.

As quick test, you can select alsa device in the backend: `unique-id=alsahw:1;0` then stop pulse service: `systemctl stop pulseaudio` (on dom0) and try to play the file.

**Comment by jsharma80** [comment]
Thanks for the pointers. I am debugging now and will revert with progress in a couple of days.

**Comment by jsharma80** [comment]
Closing this issue as ALSA back end is working for me (issue #40). Thank you for all your help.
